email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 465
  username: "mcidecouverte@gmail.com"
  password: "xojb vgnc pzre tcbl"
  sender_name: "MCI Canada"
  sender_email: "mcidecouverte@gmail.com"
  admin_recipients:
    - email: "mci360@mcigc.ca"
      name: "MCI Admin"
    - email: "placer@mcigc.ca"
      name: "MCI Placer"
